### PR TITLE
[WIP] Add HttpSys 

### PR DESCRIPTION
**Pull request by ChrSteinert**
HttpSys is an alternative to Kestrel and IIS. It enables stand alone hosting with Windows Auth - see #62 .

Let's talk about the API though. I am, in particular, unhappy with the `use_httpsys_with_args`. Any ideas?

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
> Let's talk about the API though. I am, in particular, unhappy with the use_httpsys_with_args. Any ideas?

We use `aaa_with_config` in couple of other places. While I'm also not super happy about naming, maybe at least we should try to be consistent.

**Comment by ChrSteinert** [comment]
+1 for consitency. Let me change that.

**Comment by ChrSteinert** [comment]
Ih. You merged that already? I did not make it yet to do the new naming. Should I do a new PR for that?

________________________________

**Comment by Krzysztof-Cieslak** [comment]
I'm just changing it

**Comment by Krzysztof-Cieslak** [comment]
97da6804cc1d26315b5dc73edba92a5fd101c364

**Pull request merged**
