### PR TITLE
Add Google OAuth

### LINKED ISSUE #84: Google OAuth doesn't work with use_custom_oauth
The `use_custom_oauth` operation in ApplicationBuilder uses IServiceCollection.AddOAuth() behind the scenes, but that doesn't work for Google OAuth: the Google servers will complain about a missing `scopes` parameter. The MSDN docs mention an AddGoogle function, which takes a GoogleOptions instance (derived from OAuthOptions). I've tested it, and writing a custom operation that uses AddGoogle instead of AddOAuth is enough to allow Google OAuth to work.

### PR DESCRIPTION
**Pull request by rmunn**
This fixes #84.

### CODE REVIEW

**Comment by rmunn** [comment]
Note that https://github.com/SaturnFramework/Saturn/pull/85/commits/4e5ca4519046243051c9fd8208b217fdd889494b arbitrarily picks the name `urn:google:image:url` for the claim name. Not everyone needs to store the avatar URL, so this might not be useful to everyone. But it's a piece of information that can't be handled by passing in a claim mapping in `jsonToClaimsMap`, because it involves a JSON *subkey*, not just a key. So I decided to make it available in the default configuration, since some people might find it useful (e.g., automatically displaying a proper avatar the first time a user registers for a site if they registered via Google OAuth).

**Comment by Krzysztof-Cieslak** [comment]
This is really nice, but I wonder how we should handle it from "infrastructure" point of view. Just like with #78 (and #62 discussion) I'm not sure if I want to add as many dependencies to "core" Saturn package. However, I'm also not big fan of creating seperate NuGet packages for every single on of those particular implementations.

Maybe we should do something like `Saturn.Extensions.Authentication` package where we will put helpers for some specific authentication methods? CC: @ChrSteinert

**Comment by NinoFloris** [comment]
What about a small core that can manageably get to 1.x quickly together with a labs package where a lot more lives that might not be maintained all that well or if it's actually popular gets pulled into core?

**Comment by Krzysztof-Cieslak** [comment]
Or maybe I'm just overthinking it. People nowadays are suggested to do `AspNet.All` and seems to be happy with all unnecessary stuff they get.

**Comment by rmunn** [comment]
It's probably easier to transition from things in a separate package to all-in-one, than it is to go the other way around. If people used to have to download the Saturn.Authentication.OAuth package to get Google/Facebook/Twitter OAuth working, but now they no longer have to download that package because those functions live in the main NuGet package now, they'll generally be happy about that change. Whereas if you start with everything in the main package and *then* split it out, you'll get lots of people unhappy that the code that *used* to work, now doesn't work any more after they updated to Saturn 0.7.0.

So I'm in favor of a Saturn.Authentication.OAuth package for now, and maybe a Saturn.All meta-package that just depends on all the others.

**Comment by Krzysztof-Cieslak** [comment]
Maybe `Saturn.Extensions.Authentication` (or just  Saturn.Authentication`) instead of  `Saturn.Authentication.OAuth` as something like #78 is not OAuth and doesn't really belong to core (if we're splitting)

**Comment by ChrSteinert** [comment]
Agree 100% with Chris here. Make it a `Saturn.Extension.Authentication` package.
Alas, `HttpSys` is not an auth feature, yet Windows Auth on `HttpSys` is … Quite complicated.

I would argue, that `HttpSys` hosting itself can be in core maybe, as IIS hosting is there as well. Then you can have WindowsAuth on `HttpSys` in the `Saturn.Extension.Authentication`, without further dependencies, other then core itself. Seems compelling to me!

**Pull request merged**
