### PR TITLE
Preserve stack trace by default in controller (#280)

### PR DESCRIPTION
**Pull request by retendo**
This should preserve the stack trace when exceptions are thrown while using controllers that have no dedicated error handler.

This solves a part of #280

### CODE REVIEW

**Comment by NinoFloris** [comment]
Thanks for the contribution!

A bit better, as opposed to reflection of exception internals, would be to use `ExceptionDispatchInfo.Capture(ex).Throw()` (System.Runtime.ExceptionServices)

This is the supported api to do what you want (and it's used in the F# compiler, F# core, and clr core libraries)

**Comment by retendo** [comment]
With `ExceptionDispatchInfo.Capture(ex).Throw()` there would just be a lot of added lines like
`--- End of stack trace from previous location where exception was thrown ---`.
I don't mind that, should I change it?

**Comment by NinoFloris** [comment]
Looking at the problem from a slightly different angle, it might be better to change the internal controller state to take an `ErrorHandler option`. In controllerWithErrorHandler guard on it being Some in the `try ... with ex when state.ErrorHandler.IsSome -> state.ErrorHandler.Value ex` and the compiler will then emit the EDI call :)

**Comment by retendo** [comment]
Without a fallback like this?
```FSharp
let controllerWithErrorHandler nxt ctx : HttpFuncResult =
    task {
      try
        return! initialController nxt ctx
      with
      | ex when state.ErrorHandler.IsSome -> return! state.ErrorHandler.Value ctx ex
    }
```

That would lead the exception to fall through to the router/application level, so no need for the explicit EDI call?

**Comment by NinoFloris** [comment]
Exactly! See https://github.com/dotnet/fsharp/issues/8529

**Comment by Krzysztof-Cieslak** [comment]
The same thing should be done for the Endpoint-Routing version of Controllers in https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/ControllerEndpoint.fs

**Comment by Krzysztof-Cieslak** [comment]
Published in `0.15.0-preview03`

**Pull request merged**
