### PR TITLE
Channel improvements

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
* Adds type-safety to the `Message` in `handle` action
* Renames SocketInfo to ClientInfo
* Adds the whole bunch of documentation
* Mark `SocketHub` and `SocketMiddleware` classes as internal

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
CC: @baronfel @robertpi @isaacabraham

**Comment by baronfel** [comment]
I like these changes a lot. Obviously docs are great, but the typed message handlers are nice as well.  One thing that I see being challenging is people wanting to model channel messages as DUs and then running into deserialization errors.

**Comment by Krzysztof-Cieslak** [comment]
> channel messages as DU

Well, it’s problem everywhere - in controllers, in normal http handlers. And it depends - channels are using same IJSonSerializer as any other feature so the behavior should be consistent

**Comment by robertpi** [comment]
Looks good to me, all I was doing was using the json serialize to deszeialize the message, so will save me a few lines.

**Pull request merged**
