### PR TITLE
Added unit test for deletef request

### PR DESCRIPTION
**Pull request by OnofreTZK**
# Description
With this PR I'm adding more test scenarios for the router feature. The endpoint that was added to cover the following HTTP verbs:

* DELETEF

Let me know if you guys have any suggestions.

### CODE REVIEW

**Comment by 64J0** [comment]
Nice! 🚀

**Review by cartermp — APPROVED** [review]
Thanks!

**Comment by 64J0** [comment]
#361 must fix the GitHub Actions problem ^

**Comment by cartermp** [comment]
Thanks all

**Pull request merged**
