### PR TITLE
*_from_config custom operations in application CE

### PR DESCRIPTION
**Pull request by mvsmal**
[WebHost.CreateDefaultBuilder()](https://github.com/aspnet/MetaPackages/blob/f245512f6e68d65309b65528d479f32b34c67718/src/Microsoft.AspNetCore/WebHost.cs#L157-L176) loads application configuration from several places by default:
* `appsettings.json`
* `appsettings.{env}.json`
* Environment variables
* Command line args

It aggregates them in `IConfiguration` instance available in the `ServiceCollection`.

The idea of this PR is to provide an already loaded configuration to the configuration functions for simplification of environment differences handling.

- [x] `use_jwt_authentication_from_config`
- [x] `use_cookies_authentication_from_config`
- [x] `use_oauth_from_config`
- [x] `use_cors_from_config`

With this PR I would also like to open a discussion about other custom operations which might deserve similar approach, such as `use_config` or `forse_ssl`, but the implementation there would be different.

### CODE REVIEW

**Comment by mvsmal** [comment]
@Krzysztof-Cieslak Should I continue on this? What are your thoughts?

**Comment by mvsmal** [comment]
I am fine with rename the operations to smth shorter. I am not insisting on the naming here, more on the functionality since I really miss it in my projects. Your suggestion would be a breaking change, but maybe it's fine for version 1.0

**Comment by Krzysztof-Cieslak** [comment]
>  Your suggestion would be a breaking change

I'm definitely open to do breaking changes before 1.0 release.

**Comment by tforkmann** [comment]
@mvsmal Is this still required?

**Comment by mvsmal** [comment]
@tforkmann seems like we can live without this 😃

**Pull request closed without merging**
