### PR TITLE
[WIP] Fix the docs generation script

### PR DESCRIPTION
**Pull request by 64J0**
## Description:

With this PR my goal is to fix the `docs` generation script.

Apparently there were some big changes in packages used in this process, and this script was not updated so far.

## [WIP] How to test it?

```bash
dotnet tool restore

# don't know yet if this is necessary
# but I run it before the other commands
dotnet run -- Docs

cd docs/
dotnet fornax build
```

### CODE REVIEW

**Comment by cartermp** [comment]
I moved back to .NET 6 for the action: https://github.com/SaturnFramework/Saturn/blob/main/.github/workflows/docs.yml#L19

Any concerns with merging and iterating from there?

**Comment by 64J0** [comment]
Ack, I'll keep working considering the .NET 6 SDK. I'm actually using the version `6.0.200` as well.

**Comment by 64J0** [comment]
@baronfel @cartermp Do you know if we have some docs related to this documentation generation? 

I'm having some trouble understanding that code. And apparently, there were a bunch of major updates (at least in the `FSharp.Formatting` library), so some types are broken and I'll need to fix them.

**Comment by cartermp** [comment]
@64J0 unfortunately no, I don't know much about this particular docs tool. As for FSharp.Formatting, yes, it's undergone an incredible amount of breaking changes as well. I almost wonder if it's easier to just start entirely from scratch.

**Comment by 64J0** [comment]
FsLabOrg uses a similar strategy to build the docs with Fornax. And it's working AFAIK. Later I'll try to replicate its configuration here, at least for the build docs job.

* https://github.com/fslaborg/fslaborg.github.io

**Comment by 64J0** [comment]
Since I'm not going to keep working in this PR for a while, I decided to close it. In the future, if it's still required, I can get back when having free time.

**Pull request closed without merging**
