### PR TITLE
Update to .NET6

### PR DESCRIPTION
**Pull request by tforkmann**

### CODE REVIEW

**Comment by forki** [comment]
can you please send the paket and fake changes in a separate PR?

**Comment by Krzysztof-Cieslak** [comment]
Eh, I think those build system changes are fine.

However, we need CI updates.

**Comment by tforkmann** [comment]
This is fixed now.
https://github.com/dotnet/fsharp/issues/12359#issuecomment-965105262

Anything else missing?

**Comment by forki** [comment]
Well it's fixed in master. But not released

**Comment by cartermp** [comment]
The fix is released in the compiler that targets the VS 17.1 update, which is released, so we can re-run this and plumb it through

**Comment by cartermp** [comment]
Oh, lame, it's still a fucking preview

**Comment by isaacabraham** [comment]
My understanding was that Feb/Mar time?

**Comment by cartermp** [comment]
My experience tells me it will be a _month_, yes. But which one? Some manager in devdiv has a month on a ticket in Azure DevOps, and believes with all their heart that it'll ship that month. This has no actual bearing on when it will ship.

**Comment by isaacabraham** [comment]
I thought that the code was all ready to go and there was some release window for NET 6 coming up that it was already scheduled for. Most likely I got that wrong ;-)

**Comment by cartermp** [comment]
My experience tells me it's far less organized and planned than you'd expect.

**Comment by tforkmann** [comment]
It’s just weird that you don’t find any roadmap.

**Comment by baronfel** [comment]
Current release target for 6.0.2xx is early February, but we're still catching up from the holidays + a snafu or two with the 6.0.1xx service releases in December, so that could slip.

**Comment by cartermp** [comment]
@tforkmann roadmaps are just lies an organization agrees to tell its users 🙂

**Comment by cartermp** [comment]
Linking https://github.com/giraffe-fsharp/Giraffe/issues/500 - not that it's required per say, but there's a dependency chain I want traced

**Comment by cartermp** [comment]
Dunno, about to find out :)

**Comment by tforkmann** [comment]
Ok could you please try again? 6.0.200 got release today. Thanks :)

**Comment by tforkmann** [comment]
https://github.com/dotnet/fsharp/issues/12359#issuecomment-1042117399

Looks good :)

**Comment by cartermp** [comment]
@tforkmann I looked it over and everything looks kosher to me. README update would be needed too but that isn't critical. Anything else here you think is WIP?

**Comment by tforkmann** [comment]
@cartermp Just changed the README a bit. Could do more later. Do think there is more open issues. I added you and @baronfel as reviewer.

**Review by baronfel — DISMISSED** [review]
A couple notes about the FAKE refactoring, but otherwise LGTM.

**Comment by tforkmann** [comment]
@baronfel Hope thats how you wanted it to be implemented. Never saw that before so hope thats correct now.

**Review by cartermp — APPROVED** [review]
I like the changes! Will be excited to plumb this through, update templates, and have a few folks try it out to see if there's any issues. Test in production baby

**Comment by tforkmann** [comment]
Somehow it’s didn’t release directly … have to check why

**Comment by tforkmann** [comment]
Preview Version 0.16.0-preview03 just got release

**Comment by tforkmann** [comment]
Works for me...How about you guys?

**Pull request merged**
